services:
  - type: web
    name: iknos-be
    env: node
    region: singapore
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: ROOM_CODE_LENGTH
        value: 6
      - key: MAX_ROOM_PER_USER
        value: 5
      - key: MAX_MEMBER_PER_ROOM
        value: 10
      - key: LOCATION_UPDATE_INTERVAL_SEC
        value: 10
      - key: ROOM_EMPTY_GRACE_PERIOD_MIN
        value: 30
